---
#needs vars from spark_common

- name: stop hadoop dfs (if running)
  command: "/usr/local/hadoop/sbin/stop-dfs.sh"

- name: stop hadoop yarn (if running)
  command: "/usr/local/hadoop/sbin/stop-yarn.sh"

- name: stop spark master (if running)
  command: "/opt/spark/sbin/stop-master.sh"
  when: not use_yarn

- name: stop the slaves (if running)
  shell: "/opt/spark/sbin/stop-slaves.sh"
  when: not use_yarn
