---

- name: copy Cassandra config
  become: yes
  template: src=cassandra.yaml.j2 dest="/opt/{{ cassandra_dir}}/conf/cassandra.yaml"

- name: set user and priviliges on Cassandra
  file: path="/opt/{{ cassandra_dir}}" owner={{ hadoop_user }} group=hadoop recurse=yes
